#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-httpx
Version  : 0.21.2
Release  : 23
URL      : https://files.pythonhosted.org/packages/cc/51/3dc36938b7476c8890a55e3bc594b72ce6d33a1ac45fc3a2dbb503d301aa/httpx-0.21.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/cc/51/3dc36938b7476c8890a55e3bc594b72ce6d33a1ac45fc3a2dbb503d301aa/httpx-0.21.2.tar.gz
Summary  : The next generation HTTP client.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-httpx-bin = %{version}-%{release}
Requires: pypi-httpx-license = %{version}-%{release}
Requires: pypi-httpx-python = %{version}-%{release}
Requires: pypi-httpx-python3 = %{version}-%{release}
Requires: charset-normalizer
BuildRequires : buildreq-distutils3
Provides: httpx
Provides: httpx-python
Provides: httpx-python3
BuildRequires : charset-normalizer
BuildRequires : pypi(certifi)
BuildRequires : pypi(charset_normalizer)
BuildRequires : pypi(sniffio)

%description
<p align="center">
<a href="https://www.python-httpx.org/"><img width="350" height="208" src="https://raw.githubusercontent.com/encode/httpx/master/docs/img/butterfly.png" alt='HTTPX'></a>
</p>

%package bin
Summary: bin components for the pypi-httpx package.
Group: Binaries
Requires: pypi-httpx-license = %{version}-%{release}

%description bin
bin components for the pypi-httpx package.


%package license
Summary: license components for the pypi-httpx package.
Group: Default

%description license
license components for the pypi-httpx package.


%package python
Summary: python components for the pypi-httpx package.
Group: Default
Requires: pypi-httpx-python3 = %{version}-%{release}

%description python
python components for the pypi-httpx package.


%package python3
Summary: python3 components for the pypi-httpx package.
Group: Default
Requires: python3-core
Provides: pypi(httpx)
Requires: pypi(certifi)
Requires: pypi(charset_normalizer)
Requires: pypi(httpcore)
Requires: pypi(rfc3986)
Requires: pypi(sniffio)

%description python3
python3 components for the pypi-httpx package.


%prep
%setup -q -n httpx-0.21.2
cd %{_builddir}/httpx-0.21.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641443260
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . httpcore
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-httpx
cp %{_builddir}/httpx-0.21.2/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-httpx/2f9a422e6ae22185bd3e9cdaec727ac95ab47bbb
python3 -tt setup.py build  install --root=%{buildroot}
pypi-dep-fix.py %{buildroot} httpcore
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/httpx

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-httpx/2f9a422e6ae22185bd3e9cdaec727ac95ab47bbb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
